version: "3"
services:
  db:
    container_name: twitter_clone_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/config/:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql

  server:
    container_name: twitter_clone_server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
