inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
HashSyntax:
  EnforcedStyle: ruby19
Style/AsciiComments:
  Enabled: false
ClassAndModuleChildren:
  EnforcedStyle: compact
